from fastapi import APIRouter
from app.services import decision_service as svc

router = APIRouter(tags=["decision-rooms"])
router.add_api_route('/decision-rooms/contract', svc.decision_rooms_contract_endpoint, methods=['GET'], name='decision_rooms_contract_endpoint')
router.add_api_route('/decision-rooms/template', svc.decision_rooms_template_endpoint, methods=['GET'], name='decision_rooms_template_endpoint')
router.add_api_route('/decision-rooms/validate', svc.decision_rooms_validate_endpoint, methods=['POST'], name='decision_rooms_validate_endpoint')
router.add_api_route('/decision-rooms/decisions/{decision_id}', svc.decision_rooms_create_endpoint, methods=['POST'], name='decision_rooms_create_endpoint')
router.add_api_route('/decision-rooms/decisions/{decision_id}', svc.decision_rooms_get_by_decision_endpoint, methods=['GET'], name='decision_rooms_get_by_decision_endpoint')
router.add_api_route('/decision-rooms/{room_id}', svc.decision_rooms_get_endpoint, methods=['GET'], name='decision_rooms_get_endpoint')
router.add_api_route('/decision-rooms/{room_id}', svc.decision_rooms_patch_endpoint, methods=['PATCH'], name='decision_rooms_patch_endpoint')
router.add_api_route('/decision-rooms/{room_id}/members', svc.decision_rooms_members_endpoint, methods=['GET'], name='decision_rooms_members_endpoint')
router.add_api_route('/decision-rooms/{room_id}/members', svc.decision_rooms_add_member_endpoint, methods=['POST'], name='decision_rooms_add_member_endpoint')
router.add_api_route('/decision-rooms/{room_id}/comments', svc.decision_rooms_comments_endpoint, methods=['GET'], name='decision_rooms_comments_endpoint')
router.add_api_route('/decision-rooms/{room_id}/comments', svc.decision_rooms_add_comment_endpoint, methods=['POST'], name='decision_rooms_add_comment_endpoint')
router.add_api_route('/decision-rooms/{room_id}/comments/{comment_id}', svc.decision_rooms_patch_comment_endpoint, methods=['PATCH'], name='decision_rooms_patch_comment_endpoint')
router.add_api_route('/decision-rooms/{room_id}/change-requests', svc.decision_rooms_change_requests_endpoint, methods=['GET'], name='decision_rooms_change_requests_endpoint')
router.add_api_route('/decision-rooms/{room_id}/change-requests', svc.decision_rooms_add_change_request_endpoint, methods=['POST'], name='decision_rooms_add_change_request_endpoint')
router.add_api_route('/decision-rooms/{room_id}/change-requests/{change_request_id}', svc.decision_rooms_patch_change_request_endpoint, methods=['PATCH'], name='decision_rooms_patch_change_request_endpoint')
router.add_api_route('/decision-rooms/{room_id}/snapshots', svc.decision_rooms_snapshots_endpoint, methods=['GET'], name='decision_rooms_snapshots_endpoint')
router.add_api_route('/decision-rooms/{room_id}/snapshots', svc.decision_rooms_create_snapshot_endpoint, methods=['POST'], name='decision_rooms_create_snapshot_endpoint')
router.add_api_route('/decision-rooms/{room_id}/share-grants', svc.decision_rooms_share_grants_endpoint, methods=['GET'], name='decision_rooms_share_grants_endpoint')
router.add_api_route('/decision-rooms/{room_id}/share-grants', svc.decision_rooms_create_share_grant_endpoint, methods=['POST'], name='decision_rooms_create_share_grant_endpoint')
router.add_api_route('/decision-rooms/{room_id}/events', svc.decision_rooms_events_endpoint, methods=['GET'], name='decision_rooms_events_endpoint')
router.add_api_route('/decision-rooms/import', svc.decision_rooms_import_endpoint, methods=['POST'], name='decision_rooms_import_endpoint')
