from fastapi import APIRouter
from app.services import decision_service as svc

router = APIRouter(tags=["evidence-analysis"])

router.add_api_route('/source-bundle/template', svc.source_bundle_template_endpoint, methods=['GET'], name='source_bundle_template_endpoint')
router.add_api_route('/evidence-bundle/template', svc.evidence_bundle_template_endpoint, methods=['GET'], name='evidence_bundle_template_endpoint')
router.add_api_route('/source-bundle/build', svc.source_bundle_build_endpoint, methods=['POST'], name='source_bundle_build_endpoint')
router.add_api_route('/evidence-bundle/build', svc.evidence_bundle_build_endpoint, methods=['POST'], name='evidence_bundle_build_endpoint')
router.add_api_route('/evidence-bundle/merge', svc.evidence_bundle_merge_endpoint, methods=['POST'], name='evidence_bundle_merge_endpoint')
router.add_api_route('/decision-packet/evidence-bundle', svc.decision_packet_evidence_bundle_endpoint, methods=['POST'], name='decision_packet_evidence_bundle_endpoint')
router.add_api_route('/criteria/template', svc.criteria_template_endpoint, methods=['GET'], name='criteria_template_endpoint')
router.add_api_route('/alternatives/template', svc.alternatives_template_endpoint, methods=['GET'], name='alternatives_template_endpoint')
router.add_api_route('/tradeoff-matrix/template', svc.tradeoff_matrix_template_endpoint, methods=['GET'], name='tradeoff_matrix_template_endpoint')
router.add_api_route('/criteria/build', svc.criteria_build_endpoint, methods=['POST'], name='criteria_build_endpoint')
router.add_api_route('/alternatives/build', svc.alternatives_build_endpoint, methods=['POST'], name='alternatives_build_endpoint')
router.add_api_route('/tradeoff-matrix/build', svc.tradeoff_matrix_build_endpoint, methods=['POST'], name='tradeoff_matrix_build_endpoint')
router.add_api_route('/decision-packet/tradeoff-matrix', svc.decision_packet_tradeoff_matrix_endpoint, methods=['POST'], name='decision_packet_tradeoff_matrix_endpoint')
router.add_api_route('/uncertainty-register/template', svc.uncertainty_register_template_endpoint, methods=['GET'], name='uncertainty_register_template_endpoint')
router.add_api_route('/sensitivity-analysis/template', svc.sensitivity_analysis_template_endpoint, methods=['GET'], name='sensitivity_analysis_template_endpoint')
router.add_api_route('/confidence-assessment/template', svc.confidence_assessment_template_endpoint, methods=['GET'], name='confidence_assessment_template_endpoint')
router.add_api_route('/uncertainty-register/build', svc.uncertainty_register_build_endpoint, methods=['POST'], name='uncertainty_register_build_endpoint')
router.add_api_route('/sensitivity-analysis/run', svc.sensitivity_analysis_run_endpoint, methods=['POST'], name='sensitivity_analysis_run_endpoint')
router.add_api_route('/confidence-assessment/build', svc.confidence_assessment_build_endpoint, methods=['POST'], name='confidence_assessment_build_endpoint')
router.add_api_route('/decision-packet/uncertainty-confidence', svc.decision_packet_uncertainty_confidence_endpoint, methods=['POST'], name='decision_packet_uncertainty_confidence_endpoint')
router.add_api_route('/scenario-set/template', svc.scenario_set_template_v250_endpoint, methods=['GET'], name='scenario_set_template_v250_endpoint')
router.add_api_route('/scenario-analysis/template', svc.scenario_comparison_template_v250_endpoint, methods=['GET'], name='scenario_comparison_template_v250_endpoint')
router.add_api_route('/stress-test-suite/template', svc.stress_test_suite_template_endpoint, methods=['GET'], name='stress_test_suite_template_endpoint')
router.add_api_route('/scenario-set/build', svc.scenario_set_build_v250_endpoint, methods=['POST'], name='scenario_set_build_v250_endpoint')
router.add_api_route('/scenario-analysis/compare', svc.scenario_compare_v250_endpoint, methods=['POST'], name='scenario_compare_v250_endpoint')
router.add_api_route('/stress-test-suite/run', svc.stress_test_suite_run_v250_endpoint, methods=['POST'], name='stress_test_suite_run_v250_endpoint')
router.add_api_route('/decision-packet/scenario-stress', svc.decision_packet_scenario_stress_v250_endpoint, methods=['POST'], name='decision_packet_scenario_stress_v250_endpoint')
